image:
  file: .gitpod.dockerfile

tasks:
  - command: npm install --legacy-peer-deps && exit 0
  - command: cd cypress && npm install && npx cypress install && gp sync-done cypress-intall && exit 0
  - name: run compose stack
    command: docker compose up
  - name: run cypress app
    command: cd cypress && gp sync-await cypress-intall && CYPRESS_BASE_URL=$(gp url 3000) npx cypress open

ports:
  - name: vnc webui
    port: 6080
    onOpen: open-browser
  - name: next
    port: 3000
    onOpen: ignore
    visibility: public
  - name: mailcatcher
    port: 1080
    onOpen: ignore
  - name: pgadmin
    port: 8081
    onOpen: ignore
  - name: cypress websocket
    port: 5900
    onOpen: ignore

