version: '3'

services:
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DBNAME}
      - DATABASE_URI=postgres://${PG_USERNAME}:${PG_PASSWORD}@127.0.0.1:5432/${PG_DBNAME}
