services:
  nextjs:
    restart: unless-stopped
    build: .
    ports:
    - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
      mailcatcher:
        condition: service_started
    environment:
      POSTGRES_URL: postgres://postgres:postgres@postgres:5432/flarepayload
      PAYLOAD_SECRET: secret
      SMTP_HOST: mailcatcher
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASS: ""

  postgres:
    restart: unless-stopped
    image: postgres:15.2
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flarepayload
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "flarepayload"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 15s


  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
    - 8081:80
    user: root
    stop_signal: SIGINT
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@flare.network
      PGADMIN_DEFAULT_PASSWORD: dev
      PGADMIN_CONFIG_SERVER_MODE: "False"
      MASTER_PASSWORD_REQUIRED: "False"
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
    volumes:
    - ./pgadmin-servers.json:/pgadmin4/servers.json:ro
    - pgadmin_data:/var/lib/pgadmin/

  mailcatcher:
    image: sj26/mailcatcher
    ports:
    - 1080:1080

volumes:
  postgres_data:
  pgadmin_data:
