FROM node:22-alpine AS builder

WORKDIR /app

RUN apk add --no-cache bash curl

COPY package.json package-lock.json ./
# Omit --production flag for TypeScript devDependencies
RUN npm ci --legacy-peer-deps

COPY src ./src
COPY migrations ./migrations
COPY public ./public
COPY next.config.mjs payload.config.ts payload-types.ts tsconfig.json .eslintrc.json .stylelintrc manualRedirects.js ./

# Environment variables must be present at build time
ARG POSTGRES_URL
ENV POSTGRES_URL=${POSTGRES_URL}
ARG PAYLOAD_SECRET
ENV PAYLOAD_SECRET=${PAYLOAD_SECRET}
ENV NEXT_TELEMETRY_DISABLED 1
ENV DEPLOY_ENV docker

RUN npm run build