const newsRedirects = [
  { source: '/request-for-proposals-multi-asset-liquid-staking-restaking-leveraging-flares-data-and-interoperability-protocols', destination: '/news/request-for-proposals-multi-asset-liquid-staking-restaking-leveraging-flares-data-and-interoperability-protocols' },
  { source: '/sparkdex-eternal-brings-perpetuals-to-flare', destination: '/news/sparkdex-eternal-brings-perpetuals-to-flare' },
  { source: '/flare-is-live-on-dune', destination: '/news/flare-is-live-on-dune' },
  { source: '/illuminate-the-flare-ecosystem', destination: '/news/illuminate-the-flare-ecosystem' },
  { source: '/a-guide-to-rflr-rewards', destination: '/news/a-guide-to-rflr-rewards' },
  { source: '/fassets-on-songbird-then-flare-starting-with-xrp', destination: '/news/fassets-on-songbird-then-flare-starting-with-xrp' },
  { source: '/defi-101-role-of-stablecoins-in-defi', destination: '/news/defi-101-role-of-stablecoins-in-defi' },
  { source: '/flare-developer-ambassadors-program', destination: '/news/flare-developer-ambassadors-program' },
  { source: '/chainpatrol-has-partnered-with-flare', destination: '/news/chainpatrol-has-partnered-with-flare' },
  { source: '/ftsov2-rewards-update', destination: '/news/ftsov2-rewards-update' },
  { source: '/vote-to-optimize-data-provider-rewards-structure', destination: '/news/vote-to-optimize-data-provider-rewards-structure' },
  { source: '/rubic-simplifies-cross-chain-swaps-on-flare', destination: '/news/rubic-simplifies-cross-chain-swaps-on-flare' },
  { source: '/fassets-beta-retro-airdrop-update', destination: '/news/fassets-beta-retro-airdrop-update' },
  { source: '/what-are-liquid-staked-tokens', destination: '/news/what-are-liquid-staked-tokens' },
  { source: '/doge-comes-to-fassets-open-beta', destination: '/news/doge-comes-to-fassets-open-beta' },
  { source: '/flare-red-date-decentralized-kyc', destination: '/news/flare-red-date-decentralized-kyc' },
  { source: '/encode-london-hackathon-fdc', destination: '/news/encode-london-hackathon-fdc' },
  { source: '/flreth-user-guide', destination: '/news/flreth-user-guide' },
  { source: '/introducing-flreth', destination: '/news/introducing-flreth' },
  { source: '/12-new-price-feeds-now-available-on-flare', destination: '/news/12-new-price-feeds-now-available-on-flare' },
  { source: '/effortless-node-deployment-flares-blockchain-machine-images-now-live-on-google-cloud', destination: '/news/effortless-node-deployment-flares-blockchain-machine-images-now-live-on-google-cloud' },
  { source: '/flare-portal-metamask-staking-alternatives', destination: '/news/flare-portal-metamask-staking-alternatives' },
  { source: '/stp-09-the-flare-data-connector-on-songbird', destination: '/news/stp-09-the-flare-data-connector-on-songbird' },
  { source: '/fassets-beacon-quest-a-helpful-guide', destination: '/news/fassets-beacon-quest-a-helpful-guide' },
  { source: '/fassets-beacon-quest', destination: '/news/fassets-beacon-quest' },
  { source: '/flare-101-series-how-does-flares-governance-work', destination: '/news/flare-101-series-how-does-flares-governance-work' },
  { source: '/new-incentives-structure-for-protocol-participation', destination: '/news/new-incentives-structure-for-protocol-participation' },
  { source: '/harnessing-flares-defi-hub', destination: '/news/harnessing-flares-defi-hub' },
  { source: '/new-flare-defi-emissions-program-provides-industry-leading-yields', destination: '/news/new-flare-defi-emissions-program-provides-industry-leading-yields' },
  { source: '/polyhedras-zkbridge-integrates-flare', destination: '/news/polyhedras-zkbridge-integrates-flare' },
  { source: '/bitcoin-support-added-to-fassets-open-beta', destination: '/news/bitcoin-support-added-to-fassets-open-beta' },
  { source: '/fassets-open-beta-relaunches-with-new-features', destination: '/news/fassets-open-beta-relaunches-with-new-features' },
  { source: '/ftsov2-more-data-delivered-faster', destination: '/news/ftsov2-more-data-delivered-faster' },
  { source: '/how-do-i-delegate-my-flare-tokens-and-earn-rewards', destination: '/news/how-do-i-delegate-my-flare-tokens-and-earn-rewards' },
  { source: '/flare-101-series-how-do-i-set-up-autoclaiming-for-my-flaredrops-and-my-delegation-rewards', destination: '/news/flare-101-series-how-do-i-set-up-autoclaiming-for-my-flaredrops-and-my-delegation-rewards' },
  { source: '/flare-101-series-what-are-flaredrops', destination: '/news/flare-101-series-what-are-flaredrops' },
  { source: '/enshrined-oracles-understanding-the-flare-time-series-oracle', destination: '/news/enshrined-oracles-understanding-the-flare-time-series-oracle' },
  { source: '/new-flare-app-now-available-for-all-ledger-hardware-wallets', destination: '/news/new-flare-app-now-available-for-all-ledger-hardware-wallets' },
  { source: '/the-role-of-fassets-in-bitcoins-future', destination: '/news/the-role-of-fassets-in-bitcoins-future' },
  { source: '/important-update-xrp-testnet-reset-fassets-beta-reset', destination: '/news/important-update-xrp-testnet-reset-fassets-beta-reset' },
  { source: '/olympics-prediction-market-game', destination: '/news/olympics-prediction-market-game' },
  { source: '/march-ecosystem-call-recap', destination: '/news/march-ecosystem-call-recap' },
  { source: '/fassets-open-beta-updates-for-agents', destination: '/news/fassets-open-beta-updates-for-agents' },
  { source: '/flare-immunefi-launch-a-comprehensive-bug-bounty-program', destination: '/news/flare-immunefi-launch-a-comprehensive-bug-bounty-program' },
  { source: '/july-ecosystem-call-recap', destination: '/news/july-ecosystem-call-recap' },
  { source: '/use-cases-enabled-by-layerzero-v2s-integration-of-flare', destination: '/news/use-cases-enabled-by-layerzero-v2s-integration-of-flare' },
  { source: '/stargate-integrates-flare-to-deliver-unified-liquidity-from-25-chains', destination: '/news/stargate-integrates-flare-to-deliver-unified-liquidity-from-25-chains' },
  { source: '/fassets-open-beta-update-demo-dapp-for-minting-now-available', destination: '/news/fassets-open-beta-update-demo-dapp-for-minting-now-available' },
  { source: '/layerzero-v2-connects-flare-to-75-chains', destination: '/news/layerzero-v2-connects-flare-to-75-chains' },
  { source: '/sparkdexs-cutting-edge-amm-perps-protocol-to-launch-on-flare', destination: '/news/sparkdexs-cutting-edge-amm-perps-protocol-to-launch-on-flare' },
  { source: '/sip-03-songbird-decentralization-and-code-upgrade', destination: '/news/sip-03-songbird-decentralization-and-code-upgrade' },
  { source: '/list-of-data-providers-supporting-the-upgraded-ftso-on-songbird', destination: '/news/list-of-data-providers-supporting-the-upgraded-ftso-on-songbird' },
  { source: '/the-flare-transaction-verifier-app-is-now-available-on-ios-and-android', destination: '/news/the-flare-transaction-verifier-app-is-now-available-on-ios-and-android' },
  { source: '/fip-09-introducing-flr-protocol-emissions', destination: '/news/fip-09-introducing-flr-protocol-emissions' },
  { source: '/june-ecosystem-call-recap', destination: '/news/june-ecosystem-call-recap' },
  { source: '/ftso-upgrade-progress-update', destination: '/news/ftso-upgrade-progress-update' },
  { source: '/defi-on-flare-boosted-by-hex-trusts-usdx-stablecoin-and-clearpool-yield-vault', destination: '/news/defi-on-flare-boosted-by-hex-trusts-usdx-stablecoin-and-clearpool-yield-vault' },
  { source: '/fip-07-add-support-for-ftso-fast-updates-to-flare', destination: '/news/fip-07-add-support-for-ftso-fast-updates-to-flare' },
  { source: '/the-fassets-open-beta-is-live', destination: '/news/the-fassets-open-beta-is-live' },
  { source: '/fip-08-define-a-process-for-the-community-to-propose-new-ftso-data-feeds', destination: '/news/fip-08-define-a-process-for-the-community-to-propose-new-ftso-data-feeds' },
  { source: '/liquid-staking-protocol-sceptre-launching-on-flare', destination: '/news/liquid-staking-protocol-sceptre-launching-on-flare' },
  { source: '/april-ecosystem-call-recap', destination: '/news/april-ecosystem-call-recap' },
  { source: '/fassets-beta-progress-update', destination: '/news/fassets-beta-progress-update' },
  { source: '/governance-proposal-stp-08-adding-new-feeds-to-the-ftso', destination: '/news/governance-proposal-stp-08-adding-new-feeds-to-the-ftso' },
  { source: '/more-data-delivered-faster-ftsov2', destination: '/news/more-data-delivered-faster-ftsov2' },
  { source: '/state-connector-upgrade-completed-on-songbird', destination: '/news/state-connector-upgrade-completed-on-songbird' },
  { source: '/governance-proposal-flare-time-series-oracle-fast-updates', destination: '/news/governance-proposal-flare-time-series-oracle-fast-updates' },
  { source: '/raindex-launches-on-flare-to-power-decentralized-cex-style-trading', destination: '/news/raindex-launches-on-flare-to-power-decentralized-cex-style-trading' },
  { source: '/web3-security-specialist-hypernative-to-provide-proactive-protection-to-the-flare-ecosystem', destination: '/news/web3-security-specialist-hypernative-to-provide-proactive-protection-to-the-flare-ecosystem' },
  { source: '/connecting-with-kinetic', destination: '/news/connecting-with-kinetic' },
  { source: '/consensus-learning-harnessing-blockchain-for-better-ai', destination: '/news/consensus-learning-harnessing-blockchain-for-better-ai' },
  { source: '/flare-hackathon-highlights-eth-oxford', destination: '/news/flare-hackathon-highlights-eth-oxford' },
  { source: '/a-quick-guide-to-secure-your-flare-experience', destination: '/news/a-quick-guide-to-secure-your-flare-experience' },
  { source: '/updates-from-the-fassets-beta-program', destination: '/news/updates-from-the-fassets-beta-program' },
  { source: '/web3tv-interview', destination: '/news/web3tv-interview' },
  { source: '/ftso-scaling-deep-dive', destination: '/news/ftso-scaling-deep-dive' },
  { source: '/backer-agreement-tokenomics', destination: '/news/backer-agreement-tokenomics' },
  { source: '/xdfi-the-worlds-first-compliant-decentralized-futures-protocol', destination: '/news/xdfi-the-worlds-first-compliant-decentralized-futures-protocol' },
  { source: '/three-key-governance-votes-on-flare-and-songbird', destination: '/news/three-key-governance-votes-on-flare-and-songbird' },
  { source: '/stake-flr-using-metamask-or-wallet-connect', destination: '/news/stake-flr-using-metamask-or-wallet-connect' },
  { source: '/choosing-infrastructure-providers-on-flare', destination: '/news/choosing-infrastructure-providers-on-flare' },
  { source: '/flare-onboards-google-cloud-as-network-validator-and-contributor-to-the-ftso', destination: '/news/flare-onboards-google-cloud-as-network-validator-and-contributor-to-the-ftso' },
  { source: '/thinking-crypto-interview', destination: '/news/thinking-crypto-interview' },
  { source: '/understanding-google-clouds-infrastructure-provider-role-on-flare', destination: '/news/understanding-google-clouds-infrastructure-provider-role-on-flare' },
  { source: '/january-anniversary-ecosystem-call-recap', destination: '/news/january-anniversary-ecosystem-call-recap' },
  { source: '/new-options-for-accessing-staking-on-flare', destination: '/news/new-options-for-accessing-staking-on-flare' },
  { source: '/2023-in-review', destination: '/news/2023-in-review' },
  { source: '/december-ecosystem-call-recap', destination: '/news/december-ecosystem-call-recap' },
  { source: '/november-ecosystem-call-recap', destination: '/news/november-ecosystem-call-recap' },
  { source: '/eth-london-hackathon-highlights', destination: '/news/eth-london-hackathon-highlights' },
  { source: '/ftso-developer-tutorial', destination: '/news/ftso-developer-tutorial' },
  { source: '/kinetic-to-introduce-lending-and-borrowing-to-flare-ecosystem', destination: '/news/kinetic-to-introduce-lending-and-borrowing-to-flare-ecosystem' },
  { source: '/top-infrastructure-providers-join-flare-to-enable-the-blockchain-for-data', destination: '/news/top-infrastructure-providers-join-flare-to-enable-the-blockchain-for-data' },
  { source: '/flare-partners-with-elliptic-to-integrate-crypto-risk-management-tools', destination: '/news/flare-partners-with-elliptic-to-integrate-crypto-risk-management-tools' },
  { source: '/beta-testing-of-fassets-has-commenced-on-flares-coston-testnet', destination: '/news/beta-testing-of-fassets-has-commenced-on-flares-coston-testnet' },
  { source: '/getting-started-on-account-abstraction-on-flare-with-etherspot-and-web3auth', destination: '/news/getting-started-on-account-abstraction-on-flare-with-etherspot-and-web3auth' },
  { source: '/what-you-should-consider-when-staking-flr', destination: '/news/what-you-should-consider-when-staking-flr' },
  { source: '/flare-partners-with-bloxico-to-introduce-reputation-score-to-the-network', destination: '/news/flare-partners-with-bloxico-to-introduce-reputation-score-to-the-network' },
  { source: '/public-staking-on-flare-is-live', destination: '/news/public-staking-on-flare-is-live' },
  { source: '/webx-in-tokyo', destination: '/news/webx-in-tokyo' },
  { source: '/join-flare-in-paris', destination: '/news/join-flare-in-paris' },
  { source: '/category/careers', destination: '/careers' },
]

const redirectList = [
  { source: '/flare-101', destination: '/' },
  { source: '/songbird', destination: '/' },
  { source: '/education-videos', destination: '/' },
  { source: '/faqs', destination: '/' },
  { source: '/tokenomics-flr-updated', destination: '/' },
  { source: '/ftso', destination: '/products/flare-time-series-oracle' },
  { source: '/dataconnector', destination: '/products/flare-data-connector' },
  { source: '/fassets', destination: '/products/fassets' },
  { source: '/whitepapers', destination: '/' },
  { source: '/start-building', destination: '/resources/developer-hub' },
  { source: '/grants', destination: '/resources/grants' },
  { source: '/start-building/#bugbounty', destination: '/resources/developer-hub' },
  { source: '/delegate', destination: '/delegate-and-stake' },
  { source: '/staking-flr', destination: '/delegate-and-stake' },
  { source: '/ecosystem', destination: '/' }, // remove in V3
  { source: '/node-set-up', destination: 'https://dev.flare.network/category/run-a-node' },
  { source: '/become-a-data-provider', destination: 'https://dev.flare.network/run-node/ftso-data-provider' },
  { source: '/contact', destination: '/resources/developer-support' },
  ...newsRedirects,
]

const manualRedirects = redirectList.map(({ source, destination, permanent = false }) => (
  {
    source,
    destination,
    permanent,
  }
))

export default manualRedirects
