/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedGrantsCountries".
 */
export type FeaturedGrantsCountries =
  | {
      country:
        | 'AF'
        | 'AX'
        | 'AL'
        | 'DZ'
        | 'AS'
        | 'AD'
        | 'AO'
        | 'AI'
        | 'AQ'
        | 'AG'
        | 'AR'
        | 'AM'
        | 'AW'
        | 'AU'
        | 'AT'
        | 'AZ'
        | 'BS'
        | 'BH'
        | 'BD'
        | 'BB'
        | 'BY'
        | 'BE'
        | 'BZ'
        | 'BJ'
        | 'BM'
        | 'BT'
        | 'BO'
        | 'BQ'
        | 'BA'
        | 'BW'
        | 'BV'
        | 'BR'
        | 'IO'
        | 'BN'
        | 'BG'
        | 'BF'
        | 'BI'
        | 'CV'
        | 'KH'
        | 'CM'
        | 'CA'
        | 'KY'
        | 'CF'
        | 'TD'
        | 'CL'
        | 'CN'
        | 'CX'
        | 'CC'
        | 'CO'
        | 'KM'
        | 'CG'
        | 'CD'
        | 'CK'
        | 'CR'
        | 'HR'
        | 'CU'
        | 'CW'
        | 'CY'
        | 'CZ'
        | 'CI'
        | 'DK'
        | 'DJ'
        | 'DM'
        | 'DO'
        | 'EC'
        | 'EG'
        | 'SV'
        | 'GQ'
        | 'ER'
        | 'EE'
        | 'SZ'
        | 'ET'
        | 'FK'
        | 'FO'
        | 'FJ'
        | 'FI'
        | 'FR'
        | 'GF'
        | 'PF'
        | 'TF'
        | 'GA'
        | 'GM'
        | 'GE'
        | 'DE'
        | 'GH'
        | 'GI'
        | 'GR'
        | 'GL'
        | 'GD'
        | 'GP'
        | 'GU'
        | 'GT'
        | 'GG'
        | 'GN'
        | 'GW'
        | 'GY'
        | 'HT'
        | 'HM'
        | 'VA'
        | 'HN'
        | 'HK'
        | 'HU'
        | 'IS'
        | 'IN'
        | 'ID'
        | 'IR'
        | 'IQ'
        | 'IE'
        | 'IM'
        | 'IL'
        | 'IT'
        | 'JM'
        | 'JP'
        | 'JE'
        | 'JO'
        | 'KZ'
        | 'KE'
        | 'KI'
        | 'KP'
        | 'KR'
        | 'KW'
        | 'KG'
        | 'LA'
        | 'LV'
        | 'LB'
        | 'LS'
        | 'LR'
        | 'LY'
        | 'LI'
        | 'LT'
        | 'LU'
        | 'MO'
        | 'MG'
        | 'MW'
        | 'MY'
        | 'MV'
        | 'ML'
        | 'MT'
        | 'MH'
        | 'MQ'
        | 'MR'
        | 'MU'
        | 'YT'
        | 'MX'
        | 'FM'
        | 'MD'
        | 'MC'
        | 'MN'
        | 'ME'
        | 'MS'
        | 'MA'
        | 'MZ'
        | 'MM'
        | 'NA'
        | 'NR'
        | 'NP'
        | 'NL'
        | 'NC'
        | 'NZ'
        | 'NI'
        | 'NE'
        | 'NG'
        | 'NU'
        | 'NF'
        | 'MK'
        | 'MP'
        | 'NO'
        | 'OM'
        | 'PK'
        | 'PW'
        | 'PS'
        | 'PA'
        | 'PG'
        | 'PY'
        | 'PE'
        | 'PH'
        | 'PN'
        | 'PL'
        | 'PT'
        | 'PR'
        | 'QA'
        | 'RO'
        | 'RU'
        | 'RW'
        | 'RE'
        | 'BL'
        | 'SH'
        | 'KN'
        | 'LC'
        | 'MF'
        | 'PM'
        | 'VC'
        | 'WS'
        | 'SM'
        | 'ST'
        | 'SA'
        | 'SN'
        | 'RS'
        | 'SC'
        | 'SL'
        | 'SG'
        | 'SX'
        | 'SK'
        | 'SI'
        | 'SB'
        | 'SO'
        | 'ZA'
        | 'GS'
        | 'SS'
        | 'ES'
        | 'LK'
        | 'SD'
        | 'SR'
        | 'SJ'
        | 'SE'
        | 'CH'
        | 'SY'
        | 'TW'
        | 'TJ'
        | 'TZ'
        | 'TH'
        | 'TL'
        | 'TG'
        | 'TK'
        | 'TO'
        | 'TT'
        | 'TN'
        | 'TR'
        | 'TM'
        | 'TC'
        | 'TV'
        | 'UG'
        | 'UA'
        | 'AE'
        | 'GB'
        | 'US'
        | 'UY'
        | 'UZ'
        | 'VU'
        | 'VE'
        | 'VN'
        | 'EH'
        | 'YE'
        | 'ZM'
        | 'ZW';
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedGrantsTopCategories".
 */
export type FeaturedGrantsTopCategories =
  | {
      type: number | GrantType;
      number?: number | null;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkBandLinks".
 */
export type LinkBandLinks =
  | {
      linkText?: string | null;
      linkUrl?: string | null;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextCards".
 */
export type ImageTextCards =
  | {
      cardImage?: (number | null) | Media;
      cardHeader?: string | null;
      cardText?: {
        root: {
          type: string;
          children: {
            type: string;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsList".
 */
export type StatsList =
  | {
      label: string;
      stat: string;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Sections".
 */
export type Sections =
  | {
      name: string;
      rows?: Rows;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Rows".
 */
export type Rows =
  | {
      rowLabel?: string | null;
      column1Data: {
        root: {
          type: string;
          children: {
            type: string;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      };
      column2Data: {
        root: {
          type: string;
          children: {
            type: string;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      };
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PointsList".
 */
export type PointsList = {
  icon?: (number | null) | Media;
  header: string;
  text: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  addLogos?: boolean | null;
  logos?:
    | {
        logo?: (number | null) | Media;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
}[];
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ApplicationProcessSteps".
 */
export type ApplicationProcessSteps =
  | {
      title: string;
      description?: {
        root: {
          type: string;
          children: {
            type: string;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      graphicTitle?: string | null;
      graphicText?: string | null;
      id?: string | null;
    }[]
  | null;

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    events: Event;
    grants: Grant;
    'grant-types': GrantType;
    pages: Page;
    users: User;
    media: Media;
    news: News;
    'news-types': NewsType;
    'news-sub-types': NewsSubType;
    people: Person;
    developerGuides: DeveloperGuide;
    developerGuideTags: DeveloperGuideTag;
    products: Product;
    'social-links': SocialLink;
    wallets: Wallet;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    events: EventsSelect<false> | EventsSelect<true>;
    grants: GrantsSelect<false> | GrantsSelect<true>;
    'grant-types': GrantTypesSelect<false> | GrantTypesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'news-types': NewsTypesSelect<false> | NewsTypesSelect<true>;
    'news-sub-types': NewsSubTypesSelect<false> | NewsSubTypesSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    developerGuides: DeveloperGuidesSelect<false> | DeveloperGuidesSelect<true>;
    developerGuideTags: DeveloperGuideTagsSelect<false> | DeveloperGuideTagsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'social-links': SocialLinksSelect<false> | SocialLinksSelect<true>;
    wallets: WalletsSelect<false> | WalletsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'es' | 'de';
  user: User & {
    collection: 'users';
  };
  jobs?: {
    tasks: unknown;
    workflows?: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  startDate: string;
  startTime?: string | null;
  endDate?: string | null;
  endTime?: string | null;
  country:
    | 'AF'
    | 'AX'
    | 'AL'
    | 'DZ'
    | 'AS'
    | 'AD'
    | 'AO'
    | 'AI'
    | 'AQ'
    | 'AG'
    | 'AR'
    | 'AM'
    | 'AW'
    | 'AU'
    | 'AT'
    | 'AZ'
    | 'BS'
    | 'BH'
    | 'BD'
    | 'BB'
    | 'BY'
    | 'BE'
    | 'BZ'
    | 'BJ'
    | 'BM'
    | 'BT'
    | 'BO'
    | 'BQ'
    | 'BA'
    | 'BW'
    | 'BV'
    | 'BR'
    | 'IO'
    | 'BN'
    | 'BG'
    | 'BF'
    | 'BI'
    | 'CV'
    | 'KH'
    | 'CM'
    | 'CA'
    | 'KY'
    | 'CF'
    | 'TD'
    | 'CL'
    | 'CN'
    | 'CX'
    | 'CC'
    | 'CO'
    | 'KM'
    | 'CG'
    | 'CD'
    | 'CK'
    | 'CR'
    | 'HR'
    | 'CU'
    | 'CW'
    | 'CY'
    | 'CZ'
    | 'CI'
    | 'DK'
    | 'DJ'
    | 'DM'
    | 'DO'
    | 'EC'
    | 'EG'
    | 'SV'
    | 'GQ'
    | 'ER'
    | 'EE'
    | 'SZ'
    | 'ET'
    | 'FK'
    | 'FO'
    | 'FJ'
    | 'FI'
    | 'FR'
    | 'GF'
    | 'PF'
    | 'TF'
    | 'GA'
    | 'GM'
    | 'GE'
    | 'DE'
    | 'GH'
    | 'GI'
    | 'GR'
    | 'GL'
    | 'GD'
    | 'GP'
    | 'GU'
    | 'GT'
    | 'GG'
    | 'GN'
    | 'GW'
    | 'GY'
    | 'HT'
    | 'HM'
    | 'VA'
    | 'HN'
    | 'HK'
    | 'HU'
    | 'IS'
    | 'IN'
    | 'ID'
    | 'IR'
    | 'IQ'
    | 'IE'
    | 'IM'
    | 'IL'
    | 'IT'
    | 'JM'
    | 'JP'
    | 'JE'
    | 'JO'
    | 'KZ'
    | 'KE'
    | 'KI'
    | 'KP'
    | 'KR'
    | 'KW'
    | 'KG'
    | 'LA'
    | 'LV'
    | 'LB'
    | 'LS'
    | 'LR'
    | 'LY'
    | 'LI'
    | 'LT'
    | 'LU'
    | 'MO'
    | 'MG'
    | 'MW'
    | 'MY'
    | 'MV'
    | 'ML'
    | 'MT'
    | 'MH'
    | 'MQ'
    | 'MR'
    | 'MU'
    | 'YT'
    | 'MX'
    | 'FM'
    | 'MD'
    | 'MC'
    | 'MN'
    | 'ME'
    | 'MS'
    | 'MA'
    | 'MZ'
    | 'MM'
    | 'NA'
    | 'NR'
    | 'NP'
    | 'NL'
    | 'NC'
    | 'NZ'
    | 'NI'
    | 'NE'
    | 'NG'
    | 'NU'
    | 'NF'
    | 'MK'
    | 'MP'
    | 'NO'
    | 'OM'
    | 'PK'
    | 'PW'
    | 'PS'
    | 'PA'
    | 'PG'
    | 'PY'
    | 'PE'
    | 'PH'
    | 'PN'
    | 'PL'
    | 'PT'
    | 'PR'
    | 'QA'
    | 'RO'
    | 'RU'
    | 'RW'
    | 'RE'
    | 'BL'
    | 'SH'
    | 'KN'
    | 'LC'
    | 'MF'
    | 'PM'
    | 'VC'
    | 'WS'
    | 'SM'
    | 'ST'
    | 'SA'
    | 'SN'
    | 'RS'
    | 'SC'
    | 'SL'
    | 'SG'
    | 'SX'
    | 'SK'
    | 'SI'
    | 'SB'
    | 'SO'
    | 'ZA'
    | 'GS'
    | 'SS'
    | 'ES'
    | 'LK'
    | 'SD'
    | 'SR'
    | 'SJ'
    | 'SE'
    | 'CH'
    | 'SY'
    | 'TW'
    | 'TJ'
    | 'TZ'
    | 'TH'
    | 'TL'
    | 'TG'
    | 'TK'
    | 'TO'
    | 'TT'
    | 'TN'
    | 'TR'
    | 'TM'
    | 'TC'
    | 'TV'
    | 'UG'
    | 'UA'
    | 'AE'
    | 'GB'
    | 'US'
    | 'UY'
    | 'UZ'
    | 'VU'
    | 'VE'
    | 'VN'
    | 'EH'
    | 'YE'
    | 'ZM'
    | 'ZW';
  location: string;
  flareInvolvement: string;
  eventLink?: string | null;
  button?: {
    buttonType?: ('announcement' | 'rsvp') | null;
    link?: string | null;
  };
  featured?: boolean | null;
  featuredHeroEyebrow?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grants".
 */
export interface Grant {
  id: number;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  logo?: (number | null) | Media;
  country:
    | 'AF'
    | 'AX'
    | 'AL'
    | 'DZ'
    | 'AS'
    | 'AD'
    | 'AO'
    | 'AI'
    | 'AQ'
    | 'AG'
    | 'AR'
    | 'AM'
    | 'AW'
    | 'AU'
    | 'AT'
    | 'AZ'
    | 'BS'
    | 'BH'
    | 'BD'
    | 'BB'
    | 'BY'
    | 'BE'
    | 'BZ'
    | 'BJ'
    | 'BM'
    | 'BT'
    | 'BO'
    | 'BQ'
    | 'BA'
    | 'BW'
    | 'BV'
    | 'BR'
    | 'IO'
    | 'BN'
    | 'BG'
    | 'BF'
    | 'BI'
    | 'CV'
    | 'KH'
    | 'CM'
    | 'CA'
    | 'KY'
    | 'CF'
    | 'TD'
    | 'CL'
    | 'CN'
    | 'CX'
    | 'CC'
    | 'CO'
    | 'KM'
    | 'CG'
    | 'CD'
    | 'CK'
    | 'CR'
    | 'HR'
    | 'CU'
    | 'CW'
    | 'CY'
    | 'CZ'
    | 'CI'
    | 'DK'
    | 'DJ'
    | 'DM'
    | 'DO'
    | 'EC'
    | 'EG'
    | 'SV'
    | 'GQ'
    | 'ER'
    | 'EE'
    | 'SZ'
    | 'ET'
    | 'FK'
    | 'FO'
    | 'FJ'
    | 'FI'
    | 'FR'
    | 'GF'
    | 'PF'
    | 'TF'
    | 'GA'
    | 'GM'
    | 'GE'
    | 'DE'
    | 'GH'
    | 'GI'
    | 'GR'
    | 'GL'
    | 'GD'
    | 'GP'
    | 'GU'
    | 'GT'
    | 'GG'
    | 'GN'
    | 'GW'
    | 'GY'
    | 'HT'
    | 'HM'
    | 'VA'
    | 'HN'
    | 'HK'
    | 'HU'
    | 'IS'
    | 'IN'
    | 'ID'
    | 'IR'
    | 'IQ'
    | 'IE'
    | 'IM'
    | 'IL'
    | 'IT'
    | 'JM'
    | 'JP'
    | 'JE'
    | 'JO'
    | 'KZ'
    | 'KE'
    | 'KI'
    | 'KP'
    | 'KR'
    | 'KW'
    | 'KG'
    | 'LA'
    | 'LV'
    | 'LB'
    | 'LS'
    | 'LR'
    | 'LY'
    | 'LI'
    | 'LT'
    | 'LU'
    | 'MO'
    | 'MG'
    | 'MW'
    | 'MY'
    | 'MV'
    | 'ML'
    | 'MT'
    | 'MH'
    | 'MQ'
    | 'MR'
    | 'MU'
    | 'YT'
    | 'MX'
    | 'FM'
    | 'MD'
    | 'MC'
    | 'MN'
    | 'ME'
    | 'MS'
    | 'MA'
    | 'MZ'
    | 'MM'
    | 'NA'
    | 'NR'
    | 'NP'
    | 'NL'
    | 'NC'
    | 'NZ'
    | 'NI'
    | 'NE'
    | 'NG'
    | 'NU'
    | 'NF'
    | 'MK'
    | 'MP'
    | 'NO'
    | 'OM'
    | 'PK'
    | 'PW'
    | 'PS'
    | 'PA'
    | 'PG'
    | 'PY'
    | 'PE'
    | 'PH'
    | 'PN'
    | 'PL'
    | 'PT'
    | 'PR'
    | 'QA'
    | 'RO'
    | 'RU'
    | 'RW'
    | 'RE'
    | 'BL'
    | 'SH'
    | 'KN'
    | 'LC'
    | 'MF'
    | 'PM'
    | 'VC'
    | 'WS'
    | 'SM'
    | 'ST'
    | 'SA'
    | 'SN'
    | 'RS'
    | 'SC'
    | 'SL'
    | 'SG'
    | 'SX'
    | 'SK'
    | 'SI'
    | 'SB'
    | 'SO'
    | 'ZA'
    | 'GS'
    | 'SS'
    | 'ES'
    | 'LK'
    | 'SD'
    | 'SR'
    | 'SJ'
    | 'SE'
    | 'CH'
    | 'SY'
    | 'TW'
    | 'TJ'
    | 'TZ'
    | 'TH'
    | 'TL'
    | 'TG'
    | 'TK'
    | 'TO'
    | 'TT'
    | 'TN'
    | 'TR'
    | 'TM'
    | 'TC'
    | 'TV'
    | 'UG'
    | 'UA'
    | 'AE'
    | 'GB'
    | 'US'
    | 'UY'
    | 'UZ'
    | 'VU'
    | 'VE'
    | 'VN'
    | 'EH'
    | 'YE'
    | 'ZM'
    | 'ZW';
  announcementLink?: string | null;
  grantCategory?: (number | GrantType)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grant-types".
 */
export interface GrantType {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title?: string | null;
  slug: string;
  hero?: PageHero;
  hideHero?: boolean | null;
  previousPage?: (number | null) | Page;
  nextPage?: (number | null) | Page;
  linkType?: string | null;
  pageBanner?: {
    togglePageBanner?: boolean | null;
    bannerText?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  devHub?: DevHub;
  teamGrid?: TeamGrid;
  walletsGrid?: WalletsGrid;
  components?:
    | (
        | Columns
        | Image
        | ImageTextGridBlock
        | RichTextBlock
        | PastFeaturedGrantsGridBlock
        | Stats
        | TableWithDrawers
        | ITalkingPoints
        | TwoColumns
        | ApplicationProcess
        | OfficialChannelsBlock
        | IRegionalLinkGrid
        | FlareDropDates
        | ITwoColumnCta
        | VideoEmbedBlock
        | ICodeCta
        | IBrandLogoRoll
      )[]
    | null;
  relatedNewsType?: (number | null) | NewsType;
  pageFooterCTA?: boolean | null;
  pageFooterCTAButton?: {
    buttonText?: string | null;
    buttonLink?: string | null;
    buttonSecondaryText?: string | null;
    buttonSecondaryLink?: string | null;
    backgroundImage?: (number | null) | Media;
    backgroundImageStyle?: ('flipped' | 'offset') | null;
  };
  pageTemplate: 'default' | 'devHub' | 'events' | 'fullWidth' | 'team' | 'wallets';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHero".
 */
export interface PageHero {
  style: 'standard' | 'protocol' | 'grants';
  headline: string;
  eyebrow?: string | null;
  buttonText?: string | null;
  buttonLink?: string | null;
  buttonSecondaryText?: string | null;
  buttonSecondaryLink?: string | null;
  backgroundImage?: (number | null) | Media;
  logo?: (number | null) | Media;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  grantsInfo?: PageHeroGrantsInfo;
  protocolInfo?: PageHeroProtocolInfo;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeroGrantsInfo".
 */
export interface PageHeroGrantsInfo {
  grantsAwarded?: number | null;
  countries?: FeaturedGrantsCountries;
  topCategories?: FeaturedGrantsTopCategories;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeroProtocolInfo".
 */
export interface PageHeroProtocolInfo {
  providers?: number | null;
  feeds?: number | null;
  stakeTokens?: number | null;
  stakeValue?: number | null;
  averageBlockTime?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DevHub".
 */
export interface DevHub {
  productsGrid?: (number | Product)[] | null;
  linkBand?: {
    linkBandTitle?: string | null;
    links?: LinkBandLinks;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  icon?: (number | null) | Media;
  shortDescription?: string | null;
  titleOverride?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamGrid".
 */
export interface TeamGrid {
  gridTitle?: string | null;
  team?: (number | Person)[] | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  fullName?: string | null;
  jobTitle?: string | null;
  headshot?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WalletsGrid".
 */
export interface WalletsGrid {
  walletsGridIntro?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  wallets?: (number | Wallet)[] | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallets".
 */
export interface Wallet {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  walletLink: string;
  flrFunctionality?: boolean | null;
  walletConnect?: boolean | null;
  tags?: ('wrap' | 'delegate' | 'stake' | 'autoclaim' | 'claim' | 'voting')[] | null;
  platforms?: ('iOS' | 'Android' | 'Hardware')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Columns".
 */
export interface Columns {
  layout?: ('equal' | 'wideLeft' | 'wideRight') | null;
  alignColumns?: boolean | null;
  leftColumnBlock?:
    | (
        | {
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'colImage';
          }
        | RichText
      )[]
    | null;
  rightColumnBlock?:
    | (
        | {
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'colImage';
          }
        | RichText
      )[]
    | null;
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'columns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichText".
 */
export interface RichText {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Image".
 */
export interface Image {
  image?: (number | null) | Media;
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextGridBlock".
 */
export interface ImageTextGridBlock {
  imageTextGridTitle?: string | null;
  imageTextCardGrid?: ImageTextCards;
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageTextGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richTextBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PastFeaturedGrantsGridBlock".
 */
export interface PastFeaturedGrantsGridBlock {
  gridTitle?: string | null;
  grantsGrid?: (number | Grant)[] | null;
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pastFeaturedGrantsGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Stats".
 */
export interface Stats {
  stats?: StatsList;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Table with Drawers".
 */
export interface TableWithDrawers {
  column1Header: string;
  column2Header: string;
  sections?: Sections;
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tableDrawers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ITalkingPoints".
 */
export interface ITalkingPoints {
  variation: 'standard' | 'textualGrid' | 'wideList';
  points: PointsList;
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'talkingPoints';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "twoColumns".
 */
export interface TwoColumns {
  layout?: ('default' | 'reverse' | 'even') | null;
  ColumnOne?: {
    contentType?: ('image' | 'text') | null;
    image?: (number | null) | Media;
    text?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    imageAlignment?: ('center' | 'left' | 'right') | null;
    imageFill?: ('contain' | 'cover') | null;
  };
  ColumnTwo?: {
    contentType?: ('image' | 'text') | null;
    image?: (number | null) | Media;
    text?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    imageAlignment?: ('center' | 'left' | 'right') | null;
    imageFill?: ('contain' | 'cover') | null;
  };
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'twoColumn';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ApplicationProcess".
 */
export interface ApplicationProcess {
  title?: string | null;
  steps?: ApplicationProcessSteps;
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'applicationProcess';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfficialChannelsBlock".
 */
export interface OfficialChannelsBlock {
  title?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  channels?: (number | SocialLink)[] | null;
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'officialChannels';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links".
 */
export interface SocialLink {
  id: number;
  title: string;
  url: string;
  icon?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IRegionalLinkGrid".
 */
export interface IRegionalLinkGrid {
  title?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: string;
        name: string;
        translatedName?: string | null;
        country?:
          | (
              | 'AF'
              | 'AX'
              | 'AL'
              | 'DZ'
              | 'AS'
              | 'AD'
              | 'AO'
              | 'AI'
              | 'AQ'
              | 'AG'
              | 'AR'
              | 'AM'
              | 'AW'
              | 'AU'
              | 'AT'
              | 'AZ'
              | 'BS'
              | 'BH'
              | 'BD'
              | 'BB'
              | 'BY'
              | 'BE'
              | 'BZ'
              | 'BJ'
              | 'BM'
              | 'BT'
              | 'BO'
              | 'BQ'
              | 'BA'
              | 'BW'
              | 'BV'
              | 'BR'
              | 'IO'
              | 'BN'
              | 'BG'
              | 'BF'
              | 'BI'
              | 'CV'
              | 'KH'
              | 'CM'
              | 'CA'
              | 'KY'
              | 'CF'
              | 'TD'
              | 'CL'
              | 'CN'
              | 'CX'
              | 'CC'
              | 'CO'
              | 'KM'
              | 'CG'
              | 'CD'
              | 'CK'
              | 'CR'
              | 'HR'
              | 'CU'
              | 'CW'
              | 'CY'
              | 'CZ'
              | 'CI'
              | 'DK'
              | 'DJ'
              | 'DM'
              | 'DO'
              | 'EC'
              | 'EG'
              | 'SV'
              | 'GQ'
              | 'ER'
              | 'EE'
              | 'SZ'
              | 'ET'
              | 'FK'
              | 'FO'
              | 'FJ'
              | 'FI'
              | 'FR'
              | 'GF'
              | 'PF'
              | 'TF'
              | 'GA'
              | 'GM'
              | 'GE'
              | 'DE'
              | 'GH'
              | 'GI'
              | 'GR'
              | 'GL'
              | 'GD'
              | 'GP'
              | 'GU'
              | 'GT'
              | 'GG'
              | 'GN'
              | 'GW'
              | 'GY'
              | 'HT'
              | 'HM'
              | 'VA'
              | 'HN'
              | 'HK'
              | 'HU'
              | 'IS'
              | 'IN'
              | 'ID'
              | 'IR'
              | 'IQ'
              | 'IE'
              | 'IM'
              | 'IL'
              | 'IT'
              | 'JM'
              | 'JP'
              | 'JE'
              | 'JO'
              | 'KZ'
              | 'KE'
              | 'KI'
              | 'KP'
              | 'KR'
              | 'KW'
              | 'KG'
              | 'LA'
              | 'LV'
              | 'LB'
              | 'LS'
              | 'LR'
              | 'LY'
              | 'LI'
              | 'LT'
              | 'LU'
              | 'MO'
              | 'MG'
              | 'MW'
              | 'MY'
              | 'MV'
              | 'ML'
              | 'MT'
              | 'MH'
              | 'MQ'
              | 'MR'
              | 'MU'
              | 'YT'
              | 'MX'
              | 'FM'
              | 'MD'
              | 'MC'
              | 'MN'
              | 'ME'
              | 'MS'
              | 'MA'
              | 'MZ'
              | 'MM'
              | 'NA'
              | 'NR'
              | 'NP'
              | 'NL'
              | 'NC'
              | 'NZ'
              | 'NI'
              | 'NE'
              | 'NG'
              | 'NU'
              | 'NF'
              | 'MK'
              | 'MP'
              | 'NO'
              | 'OM'
              | 'PK'
              | 'PW'
              | 'PS'
              | 'PA'
              | 'PG'
              | 'PY'
              | 'PE'
              | 'PH'
              | 'PN'
              | 'PL'
              | 'PT'
              | 'PR'
              | 'QA'
              | 'RO'
              | 'RU'
              | 'RW'
              | 'RE'
              | 'BL'
              | 'SH'
              | 'KN'
              | 'LC'
              | 'MF'
              | 'PM'
              | 'VC'
              | 'WS'
              | 'SM'
              | 'ST'
              | 'SA'
              | 'SN'
              | 'RS'
              | 'SC'
              | 'SL'
              | 'SG'
              | 'SX'
              | 'SK'
              | 'SI'
              | 'SB'
              | 'SO'
              | 'ZA'
              | 'GS'
              | 'SS'
              | 'ES'
              | 'LK'
              | 'SD'
              | 'SR'
              | 'SJ'
              | 'SE'
              | 'CH'
              | 'SY'
              | 'TW'
              | 'TJ'
              | 'TZ'
              | 'TH'
              | 'TL'
              | 'TG'
              | 'TK'
              | 'TO'
              | 'TT'
              | 'TN'
              | 'TR'
              | 'TM'
              | 'TC'
              | 'TV'
              | 'UG'
              | 'UA'
              | 'AE'
              | 'GB'
              | 'US'
              | 'UY'
              | 'UZ'
              | 'VU'
              | 'VE'
              | 'VN'
              | 'EH'
              | 'YE'
              | 'ZM'
              | 'ZW'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'regionalLinkGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FlareDropDates".
 */
export interface FlareDropDates {
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'flareDropDates';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ITwoColumnCta".
 */
export interface ITwoColumnCta {
  image?: (number | null) | Media;
  eyebrow?: string | null;
  header?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  primaryButtonText?: string | null;
  primaryButtonLink?: string | null;
  secondaryButtonText?: string | null;
  secondaryButtonLink?: string | null;
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'twoColumnCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock".
 */
export interface VideoEmbedBlock {
  title?: string | null;
  url?: string | null;
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoEmbedBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ICodeCta".
 */
export interface ICodeCta {
  header?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  buttonText?: string | null;
  buttonLink?: string | null;
  buttonSecondaryText?: string | null;
  buttonSecondaryLink?: string | null;
  hideCode?: boolean | null;
  image?: (number | null) | Media;
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'codeCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IBrandLogoRoll".
 */
export interface IBrandLogoRoll {
  header?: string | null;
  logos?:
    | {
        image?: (number | null) | Media;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  createSideNavLink?: boolean | null;
  linkText?: string | null;
  blockMarginSettings?: boolean | null;
  standardTopMargin?: boolean | null;
  standardBottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'brandLogoRoll';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-types".
 */
export interface NewsType {
  id: number;
  title: string;
  slug: string;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title?: string | null;
  slug: string;
  excerpt?: string | null;
  publishDate: string;
  author: number | User;
  type: number | NewsType;
  subtype?: (number | null) | NewsSubType;
  contentType?: ('video' | 'podcast') | null;
  relatedPosts?: (number | News)[] | null;
  teaserThumbnail?: (number | null) | Media;
  logos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-sub-types".
 */
export interface NewsSubType {
  id: number;
  title: string;
  slug: string;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developerGuides".
 */
export interface DeveloperGuide {
  id: number;
  title: string;
  shortDescription?: string | null;
  guideLink: string;
  tags?: (number | DeveloperGuideTag)[] | null;
  product?: (number | null) | Product;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developerGuideTags".
 */
export interface DeveloperGuideTag {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'grants';
        value: number | Grant;
      } | null)
    | ({
        relationTo: 'grant-types';
        value: number | GrantType;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'news-types';
        value: number | NewsType;
      } | null)
    | ({
        relationTo: 'news-sub-types';
        value: number | NewsSubType;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'developerGuides';
        value: number | DeveloperGuide;
      } | null)
    | ({
        relationTo: 'developerGuideTags';
        value: number | DeveloperGuideTag;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'social-links';
        value: number | SocialLink;
      } | null)
    | ({
        relationTo: 'wallets';
        value: number | Wallet;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  startDate?: T;
  startTime?: T;
  endDate?: T;
  endTime?: T;
  country?: T;
  location?: T;
  flareInvolvement?: T;
  eventLink?: T;
  button?:
    | T
    | {
        buttonType?: T;
        link?: T;
      };
  featured?: T;
  featuredHeroEyebrow?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grants_select".
 */
export interface GrantsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  logo?: T;
  country?: T;
  announcementLink?: T;
  grantCategory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grant-types_select".
 */
export interface GrantTypesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        style?: T;
        headline?: T;
        eyebrow?: T;
        buttonText?: T;
        buttonLink?: T;
        buttonSecondaryText?: T;
        buttonSecondaryLink?: T;
        backgroundImage?: T;
        logo?: T;
        text?: T;
        grantsInfo?:
          | T
          | {
              grantsAwarded?: T;
              countries?:
                | T
                | {
                    country?: T;
                    id?: T;
                  };
              topCategories?:
                | T
                | {
                    type?: T;
                    number?: T;
                    id?: T;
                  };
            };
        protocolInfo?:
          | T
          | {
              providers?: T;
              feeds?: T;
              stakeTokens?: T;
              stakeValue?: T;
              averageBlockTime?: T;
            };
      };
  hideHero?: T;
  previousPage?: T;
  nextPage?: T;
  linkType?: T;
  pageBanner?:
    | T
    | {
        togglePageBanner?: T;
        bannerText?: T;
      };
  devHub?:
    | T
    | {
        productsGrid?: T;
        linkBand?:
          | T
          | {
              linkBandTitle?: T;
              links?:
                | T
                | {
                    linkText?: T;
                    linkUrl?: T;
                    id?: T;
                  };
            };
      };
  teamGrid?:
    | T
    | {
        gridTitle?: T;
        team?: T;
      };
  walletsGrid?:
    | T
    | {
        walletsGridIntro?: T;
        wallets?: T;
      };
  components?:
    | T
    | {
        columns?:
          | T
          | {
              layout?: T;
              alignColumns?: T;
              leftColumnBlock?:
                | T
                | {
                    colImage?:
                      | T
                      | {
                          image?: T;
                          id?: T;
                          blockName?: T;
                        };
                    richText?:
                      | T
                      | {
                          richText?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              rightColumnBlock?:
                | T
                | {
                    colImage?:
                      | T
                      | {
                          image?: T;
                          id?: T;
                          blockName?: T;
                        };
                    richText?:
                      | T
                      | {
                          richText?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        imageTextGrid?:
          | T
          | {
              imageTextGridTitle?: T;
              imageTextCardGrid?:
                | T
                | {
                    cardImage?: T;
                    cardHeader?: T;
                    cardText?: T;
                    id?: T;
                  };
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        richTextBlock?:
          | T
          | {
              richText?: T;
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        pastFeaturedGrantsGrid?:
          | T
          | {
              gridTitle?: T;
              grantsGrid?: T;
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              stats?:
                | T
                | {
                    label?: T;
                    stat?: T;
                    id?: T;
                  };
              caption?: T;
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        tableDrawers?:
          | T
          | {
              column1Header?: T;
              column2Header?: T;
              sections?:
                | T
                | {
                    name?: T;
                    rows?:
                      | T
                      | {
                          rowLabel?: T;
                          column1Data?: T;
                          column2Data?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        talkingPoints?:
          | T
          | {
              variation?: T;
              points?:
                | T
                | {
                    icon?: T;
                    header?: T;
                    text?: T;
                    addLogos?: T;
                    logos?:
                      | T
                      | {
                          logo?: T;
                          link?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        twoColumn?:
          | T
          | {
              layout?: T;
              ColumnOne?:
                | T
                | {
                    contentType?: T;
                    image?: T;
                    text?: T;
                    imageAlignment?: T;
                    imageFill?: T;
                  };
              ColumnTwo?:
                | T
                | {
                    contentType?: T;
                    image?: T;
                    text?: T;
                    imageAlignment?: T;
                    imageFill?: T;
                  };
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        applicationProcess?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    graphicTitle?: T;
                    graphicText?: T;
                    id?: T;
                  };
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        officialChannels?:
          | T
          | {
              title?: T;
              text?: T;
              channels?: T;
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        regionalLinkGrid?:
          | T
          | {
              title?: T;
              description?: T;
              links?:
                | T
                | {
                    link?: T;
                    name?: T;
                    translatedName?: T;
                    country?: T;
                    id?: T;
                  };
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        flareDropDates?:
          | T
          | {
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        twoColumnCta?:
          | T
          | {
              image?: T;
              eyebrow?: T;
              header?: T;
              text?: T;
              primaryButtonText?: T;
              primaryButtonLink?: T;
              secondaryButtonText?: T;
              secondaryButtonLink?: T;
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        videoEmbedBlock?:
          | T
          | {
              title?: T;
              url?: T;
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        codeCta?:
          | T
          | {
              header?: T;
              text?: T;
              buttonText?: T;
              buttonLink?: T;
              buttonSecondaryText?: T;
              buttonSecondaryLink?: T;
              hideCode?: T;
              image?: T;
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        brandLogoRoll?:
          | T
          | {
              header?: T;
              logos?:
                | T
                | {
                    image?: T;
                    link?: T;
                    id?: T;
                  };
              createSideNavLink?: T;
              linkText?: T;
              blockMarginSettings?: T;
              standardTopMargin?: T;
              standardBottomMargin?: T;
              id?: T;
              blockName?: T;
            };
      };
  relatedNewsType?: T;
  pageFooterCTA?: T;
  pageFooterCTAButton?:
    | T
    | {
        buttonText?: T;
        buttonLink?: T;
        buttonSecondaryText?: T;
        buttonSecondaryLink?: T;
        backgroundImage?: T;
        backgroundImageStyle?: T;
      };
  pageTemplate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  publishDate?: T;
  author?: T;
  type?: T;
  subtype?: T;
  contentType?: T;
  relatedPosts?: T;
  teaserThumbnail?: T;
  logos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  featured?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-types_select".
 */
export interface NewsTypesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-sub-types_select".
 */
export interface NewsSubTypesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  fullName?: T;
  jobTitle?: T;
  headshot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developerGuides_select".
 */
export interface DeveloperGuidesSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  guideLink?: T;
  tags?: T;
  product?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developerGuideTags_select".
 */
export interface DeveloperGuideTagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  shortDescription?: T;
  titleOverride?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallets_select".
 */
export interface WalletsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  walletLink?: T;
  flrFunctionality?: T;
  walletConnect?: T;
  tags?: T;
  platforms?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}